id = "cyxcode"
name = "CyxCode"
description = "The open source coding agent."
version = "1.3.2"
schema_version = 1
authors = ["code3hr"]
repository = "https://github.com/code3hr/cyxcode"

[agent_servers.cyxcode]
name = "CyxCode"
icon = "./icons/cyxcode.svg"

[agent_servers.opencode.targets.darwin-aarch64]
archive = "https://github.com/code3hr/cyxcode/releases/download/v1.3.2/cyxcode-darwin-arm64.zip"
cmd = "./cyxcode"
args = ["acp"]

[agent_servers.opencode.targets.darwin-x86_64]
archive = "https://github.com/code3hr/cyxcode/releases/download/v1.3.2/cyxcode-darwin-x64.zip"
cmd = "./cyxcode"
args = ["acp"]

[agent_servers.opencode.targets.linux-aarch64]
archive = "https://github.com/code3hr/cyxcode/releases/download/v1.3.2/cyxcode-linux-arm64.tar.gz"
cmd = "./cyxcode"
args = ["acp"]

[agent_servers.opencode.targets.linux-x86_64]
archive = "https://github.com/code3hr/cyxcode/releases/download/v1.3.2/cyxcode-linux-x64.tar.gz"
cmd = "./cyxcode"
args = ["acp"]

[agent_servers.opencode.targets.windows-x86_64]
archive = "https://github.com/code3hr/cyxcode/releases/download/v1.3.2/cyxcode-windows-x64.zip"
cmd = "./cyxcode.exe"
args = ["acp"]
