#!/bin/bash
set -e

case "$1" in
    purge)
        # Remove configuration and data
        rm -rf /usr/lib/cyxcode
        rm -rf /var/lib/cyxcode
        rm -rf /var/log/cyxcode
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
